# Generated by Django 4.1.7 on 2023-03-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truyen', '0005_alter_truyen_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rating',
            new_name='rate',
        ),
    ]
